# Generated by Django 2.2.5 on 2019-09-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayStyle',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_id', models.IntegerField()),
                ('background', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('meet', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departs',
            fields=[
                ('depart_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('depart', models.CharField(max_length=50)),
                ('var1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.TextField()),
                ('area', models.CharField(max_length=30)),
                ('counters', models.CharField(max_length=10)),
                ('meet', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meetdb',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('date2', models.CharField(max_length=20)),
                ('depart', models.CharField(max_length=20)),
                ('flag', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=30)),
                ('meet', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('sysdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.TextField()),
                ('flag', models.CharField(max_length=10)),
                ('stime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.TextField()),
                ('depart', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('user_code', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
